import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

export interface HealthMetrics {
  height: number;
  weight: number;
  bmi: number;
  growthCategory: string;
  visionScreening: string;
  lastUpdated?: string;
}

export interface NutritionData {
  mealIntakeStatus: string;
  weeklyNutritionScore: number;
  deficiencyIndicators: string[];
}

export interface MedicalRecords {
  observations: string;
  referralStatus: string;
  healthWorkerRemarks: string;
  illnessHistory?: string[];
}

export interface Student {
  id: string;
  name: string;
  age: number;
  gender: string;
  class: string;
  section: string;
  schoolName?: string;
  academicYear?: string;
  healthMetrics: HealthMetrics;
  nutritionData: NutritionData;
  medicalRecords: MedicalRecords;
}

export interface ExportOptions {
  includeNutrition?: boolean;
  includeMedical?: boolean;
  scope?: string;
  columns?: { key: string; header: string }[];
}

export const exportToPDF = (students: Student[], options: ExportOptions = {}, exportedBy = '') => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  const addWatermark = () => {
    // light diagonal watermark centered on the page
    doc.setTextColor(200, 200, 200);
    doc.setFontSize(42);
    (doc as any).setFont('helvetica', 'bold');
    doc.text('SwasthyaTrack', pageWidth / 2, pageHeight / 2, {
      angle: 45,
      align: 'center',
    } as any);
    doc.setTextColor(0, 0, 0);
  };

  const addHeader = () => {
    // Logo block (rounded) with initials
    const logoSize = 14;
    doc.setFillColor(23, 115, 102);
    doc.roundedRect(margin, 12, logoSize, logoSize, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    (doc as any).setFont('helvetica', 'bold');
    doc.text('ST', margin + logoSize / 2, 12 + logoSize / 2 + 3, { align: 'center' } as any);

    // Title and subtitle
    doc.setTextColor(23, 115, 102);
    doc.setFontSize(18);
    (doc as any).setFont('helvetica', 'bold');
    doc.text('SwasthyaTrack', margin + logoSize + 8, 20);

    doc.setTextColor(110, 110, 110);
    doc.setFontSize(10);
    (doc as any).setFont('helvetica', 'normal');
    doc.text('School Health & Nutrition Tracking System', margin + logoSize + 8, 25);

    // Report main title centered
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    (doc as any).setFont('helvetica', 'bold');
    doc.text('Student Health & Nutrition Report', pageWidth / 2, 36, { align: 'center' } as any);

    // Metadata: left column and right column
    doc.setFontSize(9);
    (doc as any).setFont('helvetica', 'normal');
    const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
    const leftY = 44;
    doc.setTextColor(80, 80, 80);
    doc.text(`School: ${students[0]?.schoolName || '—'}`, margin, leftY);
    doc.text(`Academic Year: ${students[0]?.academicYear || '—'}`, margin, leftY + 5);
    doc.text(`Total Students: ${students.length}`, margin, leftY + 10);

    // Right aligned metadata
    doc.text(`Report Generated: ${today}`, pageWidth - margin, leftY, { align: 'right' } as any);
    doc.text(`Generated By: ${exportedBy || '—'}`, pageWidth - margin, leftY + 5, { align: 'right' } as any);

    // Accented divider
    doc.setDrawColor(23, 115, 102);
    doc.setLineWidth(0.6);
    doc.line(margin, 58, pageWidth - margin, 58);
  };

  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' } as any);
    doc.text('SwasthyaTrack | Confidential Health Records', margin, pageHeight - 10);
    doc.text('Do Not Distribute', pageWidth - margin, pageHeight - 10, { align: 'right' } as any);
  };

  addWatermark();
  addHeader();

  if (students.length === 0) {
    doc.setFontSize(12);
    doc.setTextColor(150, 150, 150);
    doc.text('No data available for the selected criteria.', pageWidth / 2, 100, { align: 'center' } as any);
    addFooter(1, 1);
    doc.save(`SwasthyaTrack_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    return;
  }

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(23, 115, 102);
  // If `columns` are provided treat input as a generic tabular dataset
  if (options.columns && options.columns.length > 0) {
    doc.text((options.scope && String(options.scope)) || 'Report', margin, 70);
    const headers = options.columns.map((c) => c.header);
    const body = students.map((row: any) => options.columns!.map((c) => {
      const val = row[c.key];
      // format percentages and numbers
      if (typeof val === 'number' && Math.abs(val) <= 100 && String(val).includes('.')) return val.toString();
      return val !== undefined && val !== null ? String(val) : '—';
    }));

    (autoTable as any)(doc, {
      startY: 75,
      head: [headers],
      body,
      theme: 'grid',
      headStyles: {
        fillColor: [23, 115, 102],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: { fontSize: 9, textColor: [50, 50, 50] },
      alternateRowStyles: { fillColor: [245, 250, 249] },
      margin: { left: margin, right: margin },
    });

    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addFooter(i, totalPages);
    }
    doc.save(`SwasthyaTrack_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    return;
  }

  doc.text('Student Demographics', margin, 70);

  const demographicsData = students.map((s) => [s.id, s.name, String(s.age), s.gender, `${s.class}-${s.section}`]);

  (autoTable as any)(doc, {
    startY: 75,
    head: [['Student ID', 'Name', 'Age', 'Gender', 'Class/Section']],
    body: demographicsData,
    theme: 'grid',
    headStyles: {
      fillColor: [23, 115, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [50, 50, 50],
    },
    alternateRowStyles: {
      fillColor: [245, 250, 249],
    },
    margin: { left: margin, right: margin },
  });

  let yPosition = (doc as any).lastAutoTable?.finalY + 15 || 95;

  if (yPosition > pageHeight - 60) {
    doc.addPage();
    addWatermark();
    yPosition = 20;
  }

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(23, 115, 102);
  doc.text('Health Metrics', margin, yPosition);

  const healthData = students.map((s) => [
    s.id,
    s.name,
    `${s.healthMetrics.height} cm`,
    `${s.healthMetrics.weight} kg`,
    s.healthMetrics.bmi.toFixed(1),
    s.healthMetrics.growthCategory,
    s.healthMetrics.visionScreening,
  ]);

  (autoTable as any)(doc, {
    startY: yPosition + 5,
    head: [['ID', 'Name', 'Height', 'Weight', 'BMI', 'Growth', 'Vision']],
    body: healthData,
    theme: 'grid',
    headStyles: {
      fillColor: [23, 115, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [50, 50, 50],
    },
    alternateRowStyles: {
      fillColor: [245, 250, 249],
    },
    columnStyles: {
      5: { cellWidth: 25 },
    },
    didParseCell: (data: any) => {
      if (data.column.index === 5 && data.section === 'body') {
        const value = data.cell.raw as string;
        if (value === 'Underweight') {
          data.cell.styles.textColor = [220, 53, 69];
          data.cell.styles.fontStyle = 'bold';
        } else if (value === 'Overweight') {
          data.cell.styles.textColor = [255, 152, 0];
          data.cell.styles.fontStyle = 'bold';
        } else {
          data.cell.styles.textColor = [40, 167, 69];
        }
      }
    },
    margin: { left: margin, right: margin },
  });

  if (options.includeNutrition) {
    yPosition = (doc as any).lastAutoTable?.finalY + 15 || 95;
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      addWatermark();
      yPosition = 20;
    }
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(23, 115, 102);
    doc.text('Nutrition Data', margin, yPosition);

    const nutritionData = students.map((s) => [
      s.id,
      s.name,
      s.nutritionData.mealIntakeStatus,
      `${s.nutritionData.weeklyNutritionScore}%`,
      s.nutritionData.deficiencyIndicators.length > 0 ? s.nutritionData.deficiencyIndicators.join(', ') : '—',
    ]);

    (autoTable as any)(doc, {
      startY: yPosition + 5,
      head: [['ID', 'Name', 'Meal Status', 'Nutrition Score', 'Deficiencies']],
      body: nutritionData,
      theme: 'grid',
      headStyles: {
        fillColor: [23, 115, 102],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
      alternateRowStyles: { fillColor: [245, 250, 249] },
      margin: { left: margin, right: margin },
    });
  }

  if (options.includeMedical) {
    yPosition = (doc as any).lastAutoTable?.finalY + 15 || 95;
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      addWatermark();
      yPosition = 20;
    }
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(23, 115, 102);
    doc.text('Medical Records', margin, yPosition);

    const medicalData = students.map((s) => [
      s.id,
      s.name,
      s.medicalRecords.observations.substring(0, 30) + (s.medicalRecords.observations.length > 30 ? '...' : ''),
      s.medicalRecords.referralStatus,
      s.medicalRecords.healthWorkerRemarks.substring(0, 25) + (s.medicalRecords.healthWorkerRemarks.length > 25 ? '...' : ''),
    ]);

    (autoTable as any)(doc, {
      startY: yPosition + 5,
      head: [['ID', 'Name', 'Observations', 'Referral Status', 'Remarks']],
      body: medicalData,
      theme: 'grid',
      headStyles: {
        fillColor: [23, 115, 102],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
      alternateRowStyles: { fillColor: [245, 250, 249] },
      margin: { left: margin, right: margin },
    });
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

  doc.save(`SwasthyaTrack_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const exportToExcel = (students: Student[], options: ExportOptions = {}, exportedBy = '') => {
  const workbook = XLSX.utils.book_new();

  if (students.length === 0) {
    const emptySheet = XLSX.utils.aoa_to_sheet([['No data available for the selected criteria.']]);
    XLSX.utils.book_append_sheet(workbook, emptySheet, 'No Data');
    XLSX.writeFile(workbook, `SwasthyaTrack_Export_${new Date().toISOString().split('T')[0]}.xlsx`);
    return;
  }

  const basicInfoData = students.map((s) => ({
    'Student ID': s.id,
    'Name': s.name,
    'Age': s.age,
    'Gender': s.gender,
    'Class': s.class,
    'Section': s.section,
    'School Name': s.schoolName,
    'Academic Year': s.academicYear,
  }));
  const basicInfoSheet = XLSX.utils.json_to_sheet(basicInfoData);
  XLSX.utils.book_append_sheet(workbook, basicInfoSheet, 'Student Info');

  const healthData = students.map((s) => ({
    'Student ID': s.id,
    'Name': s.name,
    'Height (cm)': s.healthMetrics.height,
    'Weight (kg)': s.healthMetrics.weight,
    'BMI': s.healthMetrics.bmi,
    'Growth Category': s.healthMetrics.growthCategory,
    'Vision Screening': s.healthMetrics.visionScreening,
    'Last Updated': s.healthMetrics.lastUpdated,
  }));
  const healthSheet = XLSX.utils.json_to_sheet(healthData);
  XLSX.utils.book_append_sheet(workbook, healthSheet, 'Health Metrics');

  // If columns provided, create a generic sheet for the supplied rows instead of detailed sheets
  if (options.columns && options.columns.length > 0) {
    const headerRow = options.columns.map((c) => c.header);
    const dataRows = students.map((row: any) => options.columns!.map((c) => row[c.key] ?? '—'));
    const sheet = XLSX.utils.aoa_to_sheet([headerRow, ...dataRows]);
    XLSX.utils.book_append_sheet(workbook, sheet, 'Report');
    XLSX.writeFile(workbook, `SwasthyaTrack_Export_${new Date().toISOString().split('T')[0]}.xlsx`);
    return;
  }

  if (options.includeNutrition) {
    const nutritionDataSheet = students.map((s) => ({
      'Student ID': s.id,
      'Name': s.name,
      'Meal Intake Status': s.nutritionData.mealIntakeStatus,
      'Weekly Nutrition Score': s.nutritionData.weeklyNutritionScore,
      'Deficiency Indicators': s.nutritionData.deficiencyIndicators.join(', ') || '—',
    }));
    const nutritionSheet = XLSX.utils.json_to_sheet(nutritionDataSheet);
    XLSX.utils.book_append_sheet(workbook, nutritionSheet, 'Nutrition Data');
  }

  if (options.includeMedical) {
    const medicalDataSheet = students.map((s) => ({
      'Student ID': s.id,
      'Name': s.name,
      'Observations': s.medicalRecords.observations,
      'Illness History': (s.medicalRecords.illnessHistory || []).join('; ') || '—',
      'Referral Status': s.medicalRecords.referralStatus,
      'Health Worker Remarks': s.medicalRecords.healthWorkerRemarks,
    }));
    const medicalSheet = XLSX.utils.json_to_sheet(medicalDataSheet);
    XLSX.utils.book_append_sheet(workbook, medicalSheet, 'Medical Notes');
  }

  const metadataSheet = XLSX.utils.aoa_to_sheet([
    ['SwasthyaTrack - Export Metadata'],
    [''],
    ['Report Generated By', exportedBy],
    ['Export Date', new Date().toLocaleDateString('en-IN')],
    ['Export Time', new Date().toLocaleTimeString('en-IN')],
    ['Export Scope', options.scope || ''],
    ['Total Records', String(students.length)],
    ['School', students[0]?.schoolName || '—'],
    ['Academic Year', students[0]?.academicYear || '—'],
    [''],
    ['CONFIDENTIAL - Do Not Distribute Without Authorization'],
  ]);
  XLSX.utils.book_append_sheet(workbook, metadataSheet, 'Metadata');

  XLSX.writeFile(workbook, `SwasthyaTrack_Export_${new Date().toISOString().split('T')[0]}.xlsx`);
};
