CREATE TABLE "annual_health_cards" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"student_id" varchar NOT NULL,
	"year" integer NOT NULL,
	"district" text,
	"block" text,
	"school_name" text,
	"school_id" varchar,
	"mobile_health_team_id" text,
	"name_of_child" text,
	"age_years" integer,
	"age_months" integer,
	"gender" text,
	"class_section" text,
	"aadhaar_no" text,
	"pran_no" text,
	"unique_id" text,
	"father_guardian_name" text,
	"father_contact" text,
	"mother_name" text,
	"teacher_name" text,
	"teacher_contact" text,
	"weight_kg" numeric(5, 2),
	"height_cm" numeric(5, 2),
	"bmi" numeric(5, 2),
	"bmi_classification" text,
	"blood_pressure" text,
	"bp_category" text,
	"sbp" integer,
	"dbp" integer,
	"bp_classification" text,
	"vision_right" text,
	"vision_left" text,
	"visual_acuity_notes" text,
	"defect_at_birth" boolean DEFAULT false,
	"defects_at_birth" jsonb DEFAULT '[]'::jsonb,
	"a1_visible_defect" boolean DEFAULT false,
	"a1_visible_defect_notes" text,
	"deficiency_sam" boolean DEFAULT false,
	"deficiency_oedema" boolean DEFAULT false,
	"deficiency_anemia" boolean DEFAULT false,
	"deficiency_vitamin_a" boolean DEFAULT false,
	"deficiency_vitamin_d" boolean DEFAULT false,
	"deficiency_goitre" boolean DEFAULT false,
	"deficiency_obesity" boolean DEFAULT false,
	"deficiency_vitamin_b" boolean DEFAULT false,
	"deficiencies" jsonb DEFAULT '[]'::jsonb,
	"b1_severe_thinning" boolean DEFAULT false,
	"b1_referral_facility" text,
	"b1_referral_date" date,
	"b2_bilateral_oedema" boolean DEFAULT false,
	"b2_referral_facility" text,
	"b2_referral_date" date,
	"b3_severe_anemia" boolean DEFAULT false,
	"b3_referral_facility" text,
	"b3_referral_date" date,
	"b4_vitamin_a" boolean DEFAULT false,
	"b4_referral_facility" text,
	"b4_referral_date" date,
	"b5_vitamin_d" boolean DEFAULT false,
	"b5_referral_facility" text,
	"b5_referral_date" date,
	"b6_goitre" boolean DEFAULT false,
	"b6_referral_facility" text,
	"b6_referral_date" date,
	"b7_obesity" boolean DEFAULT false,
	"b7_referral_facility" text,
	"b7_referral_date" date,
	"b8_vitb_deficiency" boolean DEFAULT false,
	"b8_referral_facility" text,
	"b8_referral_date" date,
	"disease_convulsive" boolean DEFAULT false,
	"disease_otitis" boolean DEFAULT false,
	"disease_dental" boolean DEFAULT false,
	"disease_skin" boolean DEFAULT false,
	"disease_asthma" boolean DEFAULT false,
	"disease_rheumatic" boolean DEFAULT false,
	"disease_leprosy" boolean DEFAULT false,
	"disease_tuberculosis" boolean DEFAULT false,
	"diseases_flags" jsonb DEFAULT '{}'::jsonb,
	"c1" boolean DEFAULT false,
	"c1_referral_facility" text,
	"c1_referral_date" date,
	"c2" boolean DEFAULT false,
	"c2_referral_facility" text,
	"c2_referral_date" date,
	"c3" boolean DEFAULT false,
	"c3_referral_facility" text,
	"c3_referral_date" date,
	"c4" boolean DEFAULT false,
	"c4_referral_facility" text,
	"c4_referral_date" date,
	"c5" boolean DEFAULT false,
	"c5_referral_facility" text,
	"c5_referral_date" date,
	"c6" boolean DEFAULT false,
	"c6_referral_facility" text,
	"c6_referral_date" date,
	"c7" jsonb DEFAULT '{}'::jsonb,
	"c7_referral_facility" text,
	"c7_referral_date" date,
	"c8" jsonb DEFAULT '{}'::jsonb,
	"c8_referral_facility" text,
	"c8_referral_date" date,
	"development_seeing_difficulty" boolean DEFAULT false,
	"development_walking_delay" boolean DEFAULT false,
	"development_reading_writing" boolean DEFAULT false,
	"development_muscle_stiffness" boolean DEFAULT false,
	"development_hearing_difficulty" boolean DEFAULT false,
	"development_speech_difficulty" boolean DEFAULT false,
	"development_learning_difficulty" boolean DEFAULT false,
	"development_inattention" boolean DEFAULT false,
	"development_behavioral_concerns" boolean DEFAULT false,
	"developmental_flags" jsonb DEFAULT '[]'::jsonb,
	"d1" boolean DEFAULT false,
	"d1_referral_facility" text,
	"d1_referral_date" date,
	"d2" boolean DEFAULT false,
	"d2_referral_facility" text,
	"d2_referral_date" date,
	"d3" boolean DEFAULT false,
	"d3_referral_facility" text,
	"d3_referral_date" date,
	"d4" boolean DEFAULT false,
	"d4_referral_facility" text,
	"d4_referral_date" date,
	"d5" boolean DEFAULT false,
	"d5_referral_facility" text,
	"d5_referral_date" date,
	"d6" boolean DEFAULT false,
	"d6_referral_facility" text,
	"d6_referral_date" date,
	"d7" boolean DEFAULT false,
	"d7_referral_facility" text,
	"d7_referral_date" date,
	"d8" boolean DEFAULT false,
	"d8_referral_facility" text,
	"d8_referral_date" date,
	"d9" boolean DEFAULT false,
	"d9_referral_facility" text,
	"d9_referral_date" date,
	"adolescent_life_events" boolean DEFAULT false,
	"adolescent_peer_pressure" boolean DEFAULT false,
	"adolescent_sadness_fatigue" boolean DEFAULT false,
	"adolescent_menstruation" boolean DEFAULT false,
	"adolescent_burning_urination" boolean DEFAULT false,
	"adolescent_discharge" boolean DEFAULT false,
	"adolescent_menstrual_pain" boolean DEFAULT false,
	"e1_difficulty_life_events" boolean DEFAULT false,
	"e1_referral_suggested" boolean DEFAULT false,
	"e1_referral_facility" text,
	"e1_referral_date" date,
	"e2_peer_pressure" boolean DEFAULT false,
	"e2_referral_suggested" boolean DEFAULT false,
	"e2_referral_facility" text,
	"e2_referral_date" date,
	"e3_persistent_sadness" boolean DEFAULT false,
	"e3_referral_suggested" boolean DEFAULT false,
	"e3_referral_facility" text,
	"e3_referral_date" date,
	"e4_menstruation_started" boolean DEFAULT false,
	"e4_referral_suggested" boolean DEFAULT false,
	"e4_referral_facility" text,
	"e4_referral_date" date,
	"e5_pain_urination" boolean DEFAULT false,
	"e5_referral_suggested" boolean DEFAULT false,
	"e5_referral_facility" text,
	"e5_referral_date" date,
	"e6_foul_smell_discharge" boolean DEFAULT false,
	"e6_referral_suggested" boolean DEFAULT false,
	"e6_referral_facility" text,
	"e6_referral_date" date,
	"e7_severe_menstrual_pain" boolean DEFAULT false,
	"e7_referral_suggested" boolean DEFAULT false,
	"e7_referral_facility" text,
	"e7_referral_date" date,
	"adolescent_flags" jsonb DEFAULT '{}'::jsonb,
	"referral_defect_at_birth" boolean DEFAULT false,
	"referral_deficiency" boolean DEFAULT false,
	"referral_disease" boolean DEFAULT false,
	"referral_developmental" boolean DEFAULT false,
	"referral_adolescent" boolean DEFAULT false,
	"referral_recommended" boolean DEFAULT false,
	"referral_facility" text,
	"referral_doctor" text,
	"referral_date" date,
	"notes" text,
	"data_entry_by" varchar,
	"date_of_entry" timestamp DEFAULT now(),
	"status" text DEFAULT 'Pending',
	"approval_by" varchar,
	"approval_date" timestamp,
	"rejection_reason" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"c7_skin_lesions" boolean DEFAULT false,
	"c7_hypopigmented_patches" boolean DEFAULT false,
	"c7_thickened_nerves" boolean DEFAULT false,
	"c7_ulceration" boolean DEFAULT false,
	"c8_persistent_cough" boolean DEFAULT false,
	"c8_fever" boolean DEFAULT false,
	"c8_weight_loss" boolean DEFAULT false,
	"c8_lymph_node_enlargement" boolean DEFAULT false,
	CONSTRAINT "check_gender_specific_fields"
	CHECK (
  ("gender" = 'Female' AND ("e4_menstruation_started" IS NOT NULL OR "e7_severe_menstrual_pain" IS NOT NULL))
  OR "gender" != 'Female'
),
	CONSTRAINT "check_age_gated_fields"
	CHECK (
  ("age_years" >= 10 AND ("e1_difficulty_life_events" IS NOT NULL))
  OR "age_years" < 10
)
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" varchar,
	"details" jsonb DEFAULT '{}'::jsonb,
	"ip_address" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "hostel_attendance" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"student_id" varchar NOT NULL,
	"school_id" varchar NOT NULL,
	"date" date NOT NULL,
	"event_index" integer DEFAULT 0,
	"check_in_time" timestamp,
	"check_out_time" timestamp,
	"check_in_image_url" text,
	"check_out_image_url" text,
	"check_in_reason" text,
	"check_out_reason" text,
	"is_vacation" boolean DEFAULT false,
	"vacation_start_date" date,
	"vacation_end_date" date,
	"vacation_reason" text,
	"recorded_by" varchar,
	"recorder_role" text,
	"status" text DEFAULT 'Present',
	"morning_roll_call" boolean,
	"night_roll_call" boolean,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "meal_logs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"school_id" varchar NOT NULL,
	"student_id" varchar,
	"class_section" text,
	"date" date NOT NULL,
	"meal_type" text NOT NULL,
	"menu_items" jsonb DEFAULT '[]'::jsonb,
	"image_url" text,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"uploaded_by" varchar,
	"notes" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "monthly_checkups" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"student_id" varchar NOT NULL,
	"school_id" varchar NOT NULL,
	"checkup_date" date NOT NULL,
	"month" integer NOT NULL,
	"year" integer NOT NULL,
	"height_cm" numeric(5, 2),
	"weight_kg" numeric(5, 2),
	"bmi" numeric(5, 2),
	"symptoms" jsonb DEFAULT '[]'::jsonb,
	"suggested_medicines" jsonb DEFAULT '[]'::jsonb,
	"treatment_type" text DEFAULT 'Primary',
	"referred_to" text,
	"present" boolean DEFAULT true,
	"notes" text,
	"recorded_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "refresh_tokens" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "refresh_tokens_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "schools" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"code" text,
	"region" text NOT NULL,
	"district" text NOT NULL,
	"block" text NOT NULL,
	"address" text,
	"contact_phone" text,
	"contact_email" text,
	"headmaster_id" varchar,
	"total_students" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "schools_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "students" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"school_id" varchar NOT NULL,
	"unique_id" text NOT NULL,
	"aadhaar_no" text,
	"pran_no" text,
	"full_name" text NOT NULL,
	"date_of_birth" date,
	"gender" text NOT NULL,
	"class_section" text NOT NULL,
	"father_guardian_name" text,
	"father_contact" text,
	"mother_name" text,
	"mother_contact" text,
	"address" text,
	"enrollment_date" date,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "students_unique_id_unique" UNIQUE("unique_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"email" text NOT NULL,
	"full_name" text NOT NULL,
	"role" text NOT NULL,
	"school_id" varchar,
	"class_section" text,
	"district" text,
	"block" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
